-- Database schema for 2FA implementation
--
-- WARNING: This file is GENERATED from the migration files in backend-2fa/migrations/.
-- Do NOT edit this file directly. Instead, add a new migration file and then
-- regenerate this file by running:
--
--   cat migrations/*.sql | grep -v '.down.sql' | ...  (see scripts/generate-schema.sh)
--
-- The migrations/ directory is the single source of truth for the database schema.

-- ---------------------------------------------------------------------------
-- Migration 001: Schema migrations tracking table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_migrations (
    version     INTEGER PRIMARY KEY,
    name        TEXT NOT NULL,
    applied_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    checksum    TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- Migration 002: Base 2FA tables
-- ---------------------------------------------------------------------------

-- Table to store user 2FA settings
CREATE TABLE IF NOT EXISTS user_two_factor (
    user_id VARCHAR(255) PRIMARY KEY,
    secret TEXT NOT NULL,
    backup_codes TEXT NOT NULL,
    enabled BOOLEAN DEFAULT FALSE,
    algorithm VARCHAR(16) NOT NULL DEFAULT 'SHA1',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_two_factor_enabled ON user_two_factor(enabled);

-- Table to audit recovery code usage (single-use enforcement)
CREATE TABLE IF NOT EXISTS recovery_code_usage (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    code_index INT NOT NULL,
    used_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, code_index)
);

-- Audit log for 2FA admin actions and security events (Issue #688, #713)
CREATE TABLE IF NOT EXISTS two_fa_audit_log (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    event VARCHAR(100) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    metadata TEXT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON two_fa_audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON two_fa_audit_log(timestamp DESC);

-- Canary token accounts (Issue #713)
CREATE TABLE IF NOT EXISTS canary_accounts (
    user_id VARCHAR(255) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- Migration 002 (supplemental): IP access list (Issue #701)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ip_access_list (
    id          BIGSERIAL PRIMARY KEY,
    cidr        TEXT NOT NULL,
    list_type   TEXT NOT NULL CHECK (list_type IN ('allow', 'block')),
    note        TEXT,
    created_by  TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ip_access_list_type ON ip_access_list(list_type);

-- ---------------------------------------------------------------------------
-- Persistent 2FA lockout state (not yet migration-tracked)
-- Redis stores the hot failure counter, but this table is the source of truth
-- for full account lockout after 10 failures.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS two_fa_lockouts (
    user_id VARCHAR(255) PRIMARY KEY,
    failed_attempts INT NOT NULL DEFAULT 0,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    locked_at TIMESTAMP NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

