$f = 'c:\Users\DELL\Documents\GitHub\PetChain-Contracts\stellar-contracts\src\test.rs'
$lines = [System.IO.File]::ReadAllLines($f)
$newLines = [System.Collections.Generic.List[string]]::new()

# Keep lines 1..1312 (0-indexed 0..1311) — up to and including assert_eq!(slots.len(), 0);
for ($i = 0; $i -lt 1312; $i++) {
    $newLines.Add($lines[$i])
}

# Close test_book_slot and mod test
$newLines.Add('    }')
$newLines.Add('}')
$newLines.Add('')

# Write the new clean mod test_consent_upgrade
$newLines.Add('#[cfg(test)]')
$newLines.Add('mod test_consent_upgrade {')
$newLines.Add('    use crate::*;')
$newLines.Add('    use soroban_sdk::{testutils::Address as _, Address, Env, String};')
$newLines.Add('')
$newLines.Add('    fn setup_contract(env: &Env) -> (PetChainContractClient<''static>, Address) {')
$newLines.Add('        let id = env.register_contract(None, PetChainContract);')
$newLines.Add('        let client = PetChainContractClient::new(env, &id);')
$newLines.Add('        let admin = Address::generate(env);')
$newLines.Add('        client.init_admin(&admin);')
$newLines.Add('        (client, admin)')
$newLines.Add('    }')
$newLines.Add('')
$newLines.Add('    fn register_pet(client: &PetChainContractClient, env: &Env, owner: &Address) -> u64 {')
$newLines.Add('        client.register_pet(')
$newLines.Add('            owner,')
$newLines.Add('            &String::from_str(env, "Buddy"),')
$newLines.Add('            &String::from_str(env, "2020-01-01"),')
$newLines.Add('            &Gender::Male,')
$newLines.Add('            &Species::Dog,')
$newLines.Add('            &String::from_str(env, "Labrador"),')
$newLines.Add('            &String::from_str(env, "Unknown"),')
$newLines.Add('            &0u32,')
$newLines.Add('            &None,')
$newLines.Add('            &PrivacyLevel::Public,')
$newLines.Add('        )')
$newLines.Add('    }')
$newLines.Add('')
$newLines.Add('    #[test]')
$newLines.Add('    fn test_grant_consent() {')
$newLines.Add('        let env = Env::default();')
$newLines.Add('        env.mock_all_auths();')
$newLines.Add('        let (client, _admin) = setup_contract(&env);')
$newLines.Add('        let owner = Address::generate(&env);')
$newLines.Add('        let pet_id = register_pet(&client, &env, &owner);')
$newLines.Add('        let grantee = Address::generate(&env);')
$newLines.Add('        let consent_id = client.grant_consent(&pet_id, &owner, &ConsentType::Insurance, &grantee);')
$newLines.Add('        assert_eq!(consent_id, 1);')
$newLines.Add('    }')
$newLines.Add('')
$newLines.Add('    #[test]')
$newLines.Add('    fn test_get_version() {')
$newLines.Add('        let env = Env::default();')
$newLines.Add('        env.mock_all_auths();')
$newLines.Add('        let id = env.register_contract(None, PetChainContract);')
$newLines.Add('        let client = PetChainContractClient::new(&env, &id);')
$newLines.Add('        let version = client.get_version();')
$newLines.Add('        assert_eq!(version.major, 1);')
$newLines.Add('        assert_eq!(version.minor, 0);')
$newLines.Add('        assert_eq!(version.patch, 0);')
$newLines.Add('    }')
$newLines.Add('')
$newLines.Add('    #[test]')
$newLines.Add('    fn test_propose_upgrade() {')
$newLines.Add('        let env = Env::default();')
$newLines.Add('        env.mock_all_auths();')
$newLines.Add('        let (client, admin) = setup_contract(&env);')
$newLines.Add('        let owner = Address::generate(&env);')
$newLines.Add('        let pet_id = register_pet(&client, &env, &owner);')
$newLines.Add('        let grantee = Address::generate(&env);')
$newLines.Add('        let consent_id = client.grant_consent(&pet_id, &owner, &ConsentType::Insurance, &grantee);')
$newLines.Add('        assert_eq!(consent_id, 1);')
$newLines.Add('        let wasm_hash = soroban_sdk::BytesN::from_array(&env, &[0u8; 32]);')
$newLines.Add('        let proposal_id = client.propose_upgrade(&admin, &wasm_hash);')
$newLines.Add('        assert_eq!(proposal_id, 1);')
$newLines.Add('        let proposal = client.get_upgrade_proposal(&proposal_id).unwrap();')
$newLines.Add('        assert_eq!(proposal.approved, false);')
$newLines.Add('        assert_eq!(proposal.executed, false);')
$newLines.Add('    }')
$newLines.Add('')
$newLines.Add('    #[test]')
$newLines.Add('    fn test_revoke_consent() {')
$newLines.Add('        let env = Env::default();')
$newLines.Add('        env.mock_all_auths();')
$newLines.Add('        let (client, _admin) = setup_contract(&env);')
$newLines.Add('        let owner = Address::generate(&env);')
$newLines.Add('        let pet_id = register_pet(&client, &env, &owner);')
$newLines.Add('        let grantee = Address::generate(&env);')
$newLines.Add('        let consent_id = client.grant_consent(&pet_id, &owner, &ConsentType::Insurance, &grantee);')
$newLines.Add('        let revoked = client.revoke_consent(&consent_id, &owner);')
$newLines.Add('        assert!(revoked);')
$newLines.Add('    }')
$newLines.Add('')
$newLines.Add('    #[test]')
$newLines.Add('    fn test_approve_upgrade() {')
$newLines.Add('        let env = Env::default();')
$newLines.Add('        env.mock_all_auths();')
$newLines.Add('        let (client, admin) = setup_contract(&env);')
$newLines.Add('        let owner = Address::generate(&env);')
$newLines.Add('        let pet_id = register_pet(&client, &env, &owner);')
$newLines.Add('        let grantee = Address::generate(&env);')
$newLines.Add('        let consent_id = client.grant_consent(&pet_id, &owner, &ConsentType::Research, &grantee);')
$newLines.Add('        let revoked = client.revoke_consent(&consent_id, &owner);')
$newLines.Add('        assert_eq!(revoked, true);')
$newLines.Add('        let wasm_hash = soroban_sdk::BytesN::from_array(&env, &[0u8; 32]);')
$newLines.Add('        let proposal_id = client.propose_upgrade(&admin, &wasm_hash);')
$newLines.Add('        let approved = client.approve_upgrade(&proposal_id);')
$newLines.Add('        assert_eq!(approved, true);')
$newLines.Add('        let proposal = client.get_upgrade_proposal(&proposal_id).unwrap();')
$newLines.Add('        assert_eq!(proposal.approved, true);')
$newLines.Add('    }')
$newLines.Add('')
$newLines.Add('    #[test]')
$newLines.Add('    fn test_consent_history() {')
$newLines.Add('        let env = Env::default();')
$newLines.Add('        env.mock_all_auths();')
$newLines.Add('        let (client, _admin) = setup_contract(&env);')
$newLines.Add('        let owner = Address::generate(&env);')
$newLines.Add('        let pet_id = register_pet(&client, &env, &owner);')
$newLines.Add('        let grantee = Address::generate(&env);')
$newLines.Add('        client.grant_consent(&pet_id, &owner, &ConsentType::Insurance, &grantee);')
$newLines.Add('        let history = client.get_consent_history(&pet_id);')
$newLines.Add('        assert_eq!(history.len(), 1);')
$newLines.Add('    }')
$newLines.Add('')
$newLines.Add('    #[test]')
$newLines.Add('    fn test_migrate_version() {')
$newLines.Add('        let env = Env::default();')
$newLines.Add('        env.mock_all_auths();')
$newLines.Add('        let (client, _admin) = setup_contract(&env);')
$newLines.Add('        let owner = Address::generate(&env);')
$newLines.Add('        let pet_id = register_pet(&client, &env, &owner);')
$newLines.Add('        let ins = Address::generate(&env);')
$newLines.Add('        let res = Address::generate(&env);')
$newLines.Add('        client.grant_consent(&pet_id, &owner, &ConsentType::Insurance, &ins);')
$newLines.Add('        client.grant_consent(&pet_id, &owner, &ConsentType::Research, &res);')
$newLines.Add('        client.revoke_consent(&1u64, &owner);')
$newLines.Add('        let history = client.get_consent_history(&pet_id);')
$newLines.Add('        assert_eq!(history.len(), 2);')
$newLines.Add('        assert_eq!(history.get(0).unwrap().is_active, false);')
$newLines.Add('        assert_eq!(history.get(1).unwrap().is_active, true);')
$newLines.Add('    }')
$newLines.Add('')
$newLines.Add('    #[test]')
$newLines.Add('    #[should_panic]')
$newLines.Add('    fn test_upgrade_requires_admin() {')
$newLines.Add('        let env = Env::default();')
$newLines.Add('        env.mock_all_auths();')
$newLines.Add('        let id = env.register_contract(None, PetChainContract);')
$newLines.Add('        let client = PetChainContractClient::new(&env, &id);')
$newLines.Add('        let wasm_hash = soroban_sdk::BytesN::from_array(&env, &[0u8; 32]);')
$newLines.Add('        client.propose_upgrade(&Address::generate(&env), &wasm_hash);')
$newLines.Add('    }')
$newLines.Add('}')
$newLines.Add('')

# Skip old orphaned section: lines 1313..1487 (0-indexed 1312..1486)
# Then continue from line 1488 (0-indexed 1487) which is the blank line before mod test_b
$startFrom = 1487
for ($i = $startFrom; $i -lt $lines.Length; $i++) {
    $newLines.Add($lines[$i])
}

[System.IO.File]::WriteAllLines($f, $newLines)
Write-Host ('Done. Lines: ' + $newLines.Count)
