// ============================================================
// Chain-of-custody canonical digest tests (Issue: custody history)
//
// `get_custody_chain_digest` produces a SHA-256 hash chain over the
// custody history in canonical (append) order:
//
//     state = sha256(domain || u32be(version) || u64be(pet_id))
//     for each entry in chain order:
//         state = sha256(state || u32be(len(entry_bytes)) || entry_bytes)
//     digest = sha256(state || u32be(sequence))
//
// entry_bytes is the canonical serialisation of a CustodyEntry
// (see `PetChainContract::canonical_custody_entry_bytes`):
//
//     u32be(len(from_xdr)) || from_xdr
//     || u32be(len(to_xdr)) || to_xdr
//     || u64be(timestamp)
//     || u32be(transfer_type)   // Direct=0, Adoption=1, Multisig=2
//
// where from_xdr/to_xdr are the soroban Address ScVal XDR encodings
// (SCV_ADDRESS=18 || SC_ADDRESS_TYPE_ACCOUNT=0 || KEY_TYPE_ED25519=0
// || 32-byte ed25519 key, 44 bytes total for account addresses).
//
// The vectors below were generated by the reference implementation in
// scripts/gen_custody_digest_vectors.py and are *published*: they must not
// change unless the canonical format (domain/version/serialisation) changes.
// ============================================================

use crate::{
    ContractError, CustodyChainDigest, CustodyEntry, Gender, PetChainContract,
    PetChainContractClient, PrivacyLevel, Species, SystemKey, TransferType,
};
use soroban_sdk::{testutils::Address as _, Address, Env, Error, String, Vec};

// Fixed deterministic account strkeys used by the published vectors.
// A0 is the canonical all-zero ed25519 account key; A1..A3 are derived
// deterministic keys (payload == index as u32be).
const A0: &str = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF";
const A1: &str = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC6PV";
const A2: &str = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEGWF";
const A3: &str = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGO6V";

// Published digest vectors (see header comment for the construction).
const EMPTY_PET1: &str = "fd563dbadd4dc31365d995ee354f59e8156e499bb3f88618b0cd656e85bb5002";
const ONE_PET1: &str = "2ea66e7a5426d4b46fbd23238b81e91835a94c0c32b370fceef1da78db2e2701";
const TWO_PET1: &str = "ec36d1f293582df34bef1575aba01b8c12560e55771cb816d4bdc670e0135fbe";
const THREE_PET1: &str = "9357d526ad37944aae12dc8ecff7034afbd401b69e3e3913fd22fe16bd394842";
const REORDERED_PET1: &str = "1265e034f391c9233c9231c5e89fd8634401342ceef889d0bb842287dbc2f71c";
const TAMPERED_TO_PET1: &str = "f1a878686671708d444fc124e42458f6997f9845bbcf28e33c493d29c7301853";
const TWO_PET7: &str = "367ab935bd7019e3e1a96e7fa2ca8b1c30f0eb65cefed1184f3c0747fea18ae2";

fn setup(env: &Env) -> (PetChainContractClient, Address, Address) {
    env.mock_all_auths();
    env.budget().reset_unlimited();
    let contract_id = env.register_contract(None, PetChainContract);
    let client = PetChainContractClient::new(env, &contract_id);
    let owner = Address::generate(env);
    client.init_admin(&owner);
    (client, owner, contract_id)
}

fn register_pet(client: &PetChainContractClient, env: &Env, owner: &Address) -> u64 {
    client.register_pet(
        owner,
        &String::from_str(env, "Buddy"),
        &String::from_str(env, "2020-01-01"),
        &Gender::Male,
        &Species::Dog,
        &String::from_str(env, "Labrador"),
        &String::from_str(env, "Golden"),
        &30,
        &None,
        &PrivacyLevel::Public,
    )
}

fn addr(env: &Env, strkey: &str) -> Address {
    Address::from_string(&String::from_str(env, strkey))
}

fn entry(
    env: &Env,
    from: &str,
    to: &str,
    timestamp: u64,
    transfer_type: TransferType,
) -> CustodyEntry {
    CustodyEntry {
        from: addr(env, from),
        to: addr(env, to),
        timestamp,
        transfer_type,
    }
}

fn chain(env: &Env, entries: &[CustodyEntry]) -> Vec<CustodyEntry> {
    let mut v = Vec::new(env);
    for e in entries {
        v.push_back(e.clone());
    }
    v
}

fn set_custody_chain(env: &Env, contract_id: &Address, pet_id: u64, chain: &Vec<CustodyEntry>) {
    env.as_contract(contract_id, || {
        env.storage()
            .instance()
            .set(&SystemKey::CustodyChain(pet_id), chain);
    });
}

fn hex_to_array(hex: &str) -> [u8; 32] {
    let mut out = [0u8; 32];
    let bytes = hex.as_bytes();
    for i in 0..32 {
        let hi = (bytes[2 * i] as char).to_digit(16).unwrap() as u8;
        let lo = (bytes[2 * i + 1] as char).to_digit(16).unwrap() as u8;
        out[i] = (hi << 4) | lo;
    }
    out
}

fn assert_digest_equals(_env: &Env, result: &CustodyChainDigest, expected_hex: &str) {
    assert_eq!(
        result.digest.to_array(),
        hex_to_array(expected_hex),
        "digest mismatch for pet_id={} sequence={}",
        result.pet_id,
        result.sequence
    );
}

fn assert_common_fields(env: &Env, result: &CustodyChainDigest, pet_id: u64) {
    assert_eq!(
        result.domain,
        String::from_str(env, crate::CUSTODY_DIGEST_DOMAIN)
    );
    assert_eq!(result.version, crate::CUSTODY_DIGEST_VERSION);
    assert_eq!(result.pet_id, pet_id);
}

// ---------------------------------------------------------------
// Published vectors
// ---------------------------------------------------------------

#[test]
fn published_vector_empty_chain() {
    let env = Env::default();
    let (client, owner, _contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);

    let result = client.get_custody_chain_digest(&pet_id);
    assert_common_fields(&env, &result, pet_id);
    assert_eq!(result.sequence, 0);
    assert_digest_equals(&env, &result, EMPTY_PET1);
}

#[test]
fn published_vector_single_entry() {
    let env = Env::default();
    let (client, owner, contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);

    set_custody_chain(
        &env,
        &contract_id,
        pet_id,
        &chain(
            &env,
            &[entry(&env, A0, A1, 1_000_000_000, TransferType::Direct)],
        ),
    );

    let result = client.get_custody_chain_digest(&pet_id);
    assert_common_fields(&env, &result, pet_id);
    assert_eq!(result.sequence, 1);
    assert_digest_equals(&env, &result, ONE_PET1);
}

#[test]
fn published_vector_two_entries() {
    let env = Env::default();
    let (client, owner, contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);

    set_custody_chain(
        &env,
        &contract_id,
        pet_id,
        &chain(
            &env,
            &[
                entry(&env, A0, A1, 1_000_000_000, TransferType::Direct),
                entry(&env, A1, A2, 2_000_000_000, TransferType::Adoption),
            ],
        ),
    );

    let result = client.get_custody_chain_digest(&pet_id);
    assert_common_fields(&env, &result, pet_id);
    assert_eq!(result.sequence, 2);
    assert_digest_equals(&env, &result, TWO_PET1);
}

#[test]
fn published_vector_three_entries() {
    let env = Env::default();
    let (client, owner, contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);

    set_custody_chain(
        &env,
        &contract_id,
        pet_id,
        &chain(
            &env,
            &[
                entry(&env, A0, A1, 1_000_000_000, TransferType::Direct),
                entry(&env, A1, A2, 2_000_000_000, TransferType::Adoption),
                entry(&env, A2, A3, 3_000_000_000, TransferType::Multisig),
            ],
        ),
    );

    let result = client.get_custody_chain_digest(&pet_id);
    assert_common_fields(&env, &result, pet_id);
    assert_eq!(result.sequence, 3);
    assert_digest_equals(&env, &result, THREE_PET1);
}

#[test]
fn published_vector_reordered_entries() {
    let env = Env::default();
    let (client, owner, contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);

    // Same two entries as published_vector_two_entries, but swapped.
    set_custody_chain(
        &env,
        &contract_id,
        pet_id,
        &chain(
            &env,
            &[
                entry(&env, A1, A2, 2_000_000_000, TransferType::Adoption),
                entry(&env, A0, A1, 1_000_000_000, TransferType::Direct),
            ],
        ),
    );

    let result = client.get_custody_chain_digest(&pet_id);
    assert_common_fields(&env, &result, pet_id);
    assert_eq!(result.sequence, 2);
    assert_digest_equals(&env, &result, REORDERED_PET1);
    assert_ne!(result.digest.to_array(), hex_to_array(TWO_PET1));
}

#[test]
fn published_vector_tampered_to() {
    let env = Env::default();
    let (client, owner, contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);

    // Second entry's `to` differs from the canonical two-entry chain (A2 -> A3).
    set_custody_chain(
        &env,
        &contract_id,
        pet_id,
        &chain(
            &env,
            &[
                entry(&env, A0, A1, 1_000_000_000, TransferType::Direct),
                entry(&env, A1, A3, 2_000_000_000, TransferType::Adoption),
            ],
        ),
    );

    let result = client.get_custody_chain_digest(&pet_id);
    assert_common_fields(&env, &result, pet_id);
    assert_eq!(result.sequence, 2);
    assert_digest_equals(&env, &result, TAMPERED_TO_PET1);
    assert_ne!(result.digest.to_array(), hex_to_array(TWO_PET1));
}

#[test]
fn published_vector_pet_id_is_bound() {
    let env = Env::default();
    let (client, _owner, contract_id) = setup(&env);
    // No pet with id 7 is registered; the digest is a pure function of the
    // stored chain, so pet_id 7 is exercised directly.
    let pet_id: u64 = 7;

    set_custody_chain(
        &env,
        &contract_id,
        pet_id,
        &chain(
            &env,
            &[
                entry(&env, A0, A1, 1_000_000_000, TransferType::Direct),
                entry(&env, A1, A2, 2_000_000_000, TransferType::Adoption),
            ],
        ),
    );

    let result = client.get_custody_chain_digest(&pet_id);
    assert_common_fields(&env, &result, pet_id);
    assert_eq!(result.sequence, 2);
    assert_digest_equals(&env, &result, TWO_PET7);
    assert_ne!(result.digest.to_array(), hex_to_array(TWO_PET1));
}

// ---------------------------------------------------------------
// Behavioural tamper cases (no hardcoded constants)
// ---------------------------------------------------------------

fn digest_of(client: &PetChainContractClient, pet_id: u64) -> [u8; 32] {
    client.get_custody_chain_digest(&pet_id).digest.to_array()
}

#[test]
fn appending_entry_changes_digest() {
    let env = Env::default();
    let (client, owner, _contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);

    let empty = digest_of(&client, pet_id);
    assert_eq!(empty, hex_to_array(EMPTY_PET1));

    // First transfer appends one entry.
    let b = Address::generate(&env);
    client.transfer_pet(&owner, &pet_id, &b);
    let after_one = digest_of(&client, pet_id);
    assert_ne!(
        after_one, empty,
        "appending an entry must change the digest"
    );

    // Second transfer appends another entry.
    let c = Address::generate(&env);
    client.transfer_pet(&b, &pet_id, &c);
    let after_two = digest_of(&client, pet_id);
    assert_ne!(after_two, after_one, "each append must change the digest");

    assert_eq!(client.get_custody_chain_digest(&pet_id).sequence, 2);
}

#[test]
fn reordering_entries_changes_digest() {
    let env = Env::default();
    let (client, owner, contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);

    let e1 = entry(&env, A0, A1, 1_000_000_000, TransferType::Direct);
    let e2 = entry(&env, A1, A2, 2_000_000_000, TransferType::Adoption);

    set_custody_chain(
        &env,
        &contract_id,
        pet_id,
        &chain(&env, &[e1.clone(), e2.clone()]),
    );
    let ordered = digest_of(&client, pet_id);

    set_custody_chain(&env, &contract_id, pet_id, &chain(&env, &[e2, e1]));
    let reordered = digest_of(&client, pet_id);

    assert_ne!(
        ordered, reordered,
        "reordering entries must change the digest"
    );
}

#[test]
fn tampering_any_field_changes_digest() {
    let env = Env::default();
    let (client, owner, contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);

    let original = entry(&env, A0, A1, 1_000_000_000, TransferType::Direct);

    // Same entry with one field changed each time.
    let tampered_from = entry(&env, A2, A1, 1_000_000_000, TransferType::Direct);
    let tampered_to = entry(&env, A0, A2, 1_000_000_000, TransferType::Direct);
    let tampered_ts = entry(&env, A0, A1, 1_000_000_001, TransferType::Direct);
    let tampered_type = entry(&env, A0, A1, 1_000_000_000, TransferType::Adoption);

    set_custody_chain(&env, &contract_id, pet_id, &chain(&env, &[original]));
    let baseline = digest_of(&client, pet_id);

    for mutated in [tampered_from, tampered_to, tampered_ts, tampered_type] {
        set_custody_chain(&env, &contract_id, pet_id, &chain(&env, &[mutated]));
        assert_ne!(
            digest_of(&client, pet_id),
            baseline,
            "altering a custody entry field must change the digest"
        );
    }
}

// ---------------------------------------------------------------
// Bounded view + resource tests
// ---------------------------------------------------------------

/// The custody view is capped at MAX_CUSTODY_CHAIN: a full chain is
/// returned, the (cap + 1)th append is rejected with TooManyItems, and the
/// digest over the full chain reports the correct sequence.
#[test]
fn custody_chain_view_is_bounded_at_max() {
    let env = Env::default();
    let (client, owner, _contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);
    client.activate_pet(&pet_id);

    let owner_a = owner.clone();
    let owner_b = Address::generate(&env);

    // Drive the chain to its cap through the real append path.
    for i in 0..crate::MAX_CUSTODY_CHAIN {
        if i % 2 == 0 {
            client.transfer_pet(&owner_a, &pet_id, &owner_b);
        } else {
            client.transfer_pet(&owner_b, &pet_id, &owner_a);
        }
    }

    // The view is bounded: exactly MAX_CUSTODY_CHAIN entries are returned.
    let chain = client.get_custody_chain(&pet_id);
    assert_eq!(chain.len(), crate::MAX_CUSTODY_CHAIN);

    // One more append is rejected at the boundary.
    let err = client
        .try_transfer_pet(&owner_a, &pet_id, &owner_b)
        .unwrap_err()
        .unwrap();
    assert_eq!(err, Error::from(ContractError::TooManyItems));

    // The digest still computes over the full bounded chain.
    let result = client.get_custody_chain_digest(&pet_id);
    assert_eq!(result.sequence, crate::MAX_CUSTODY_CHAIN);
}

/// Digest computation over a full (cap-sized) chain is resource-bounded:
/// it completes and consumes a modest, fixed amount of CPU and memory
/// regardless of the entry contents.
#[test]
fn digest_computation_is_resource_bounded() {
    let env = Env::default();
    let (client, owner, contract_id) = setup(&env);
    let pet_id = register_pet(&client, &env, &owner);

    // Seed a full chain directly (fast path to the cap).
    let mut entries = Vec::new(&env);
    for i in 0..crate::MAX_CUSTODY_CHAIN {
        entries.push_back(entry(
            &env,
            A0,
            A1,
            1_000_000_000 + i as u64,
            TransferType::Direct,
        ));
    }
    set_custody_chain(&env, &contract_id, pet_id, &entries);

    let cpu_before = env.budget().cpu_instruction_cost();
    let mem_before = env.budget().memory_bytes_cost();

    let result = client.get_custody_chain_digest(&pet_id);

    let cpu_used = env.budget().cpu_instruction_cost() - cpu_before;
    let mem_used = env.budget().memory_bytes_cost() - mem_before;

    assert_eq!(result.sequence, crate::MAX_CUSTODY_CHAIN);
    // Native test-mode metering charges ~62M instructions for a full chain;
    // the bound is deliberately generous to catch only accidental blow-ups
    // (e.g. quadratic serialisation), not exact host costs.
    assert!(
        cpu_used < 150_000_000,
        "digest over {}-entry chain consumed too much CPU: {cpu_used}",
        crate::MAX_CUSTODY_CHAIN
    );
    // Native test-mode metering charges ~6.5MB for a full chain (per-call
    // host-object overhead, linear in entry count); the bound only guards
    // against accidental super-linear blow-ups.
    assert!(
        mem_used < 20_000_000,
        "digest over {}-entry chain consumed too much memory: {mem_used}",
        crate::MAX_CUSTODY_CHAIN
    );
}
